# --- Identificación del proyecto: REEMPLAZAR con los valores que muestra SonarCloud ---
# (Proyecto > Information, o la pantalla "Analysis Method > With GitHub Actions")
sonar.organization=SONAR_TOKEN
sonar.projectKey=f7d57eb8f38c647b56ed412de489604463e316ad

# --- Qué se analiza ---
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12

# --- Cobertura: reporte que genera pytest-cov en el step de tests ---
sonar.python.coverage.reportPaths=coverage.xml
